import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { validateJudgmentRequest, validateJudgmentResult, type JudgmentRequest, type JudgmentResult } from "./contracts.js";
import { runWorkflow, type PublicEvent } from "./workflow.js";
import type { RoleProvider } from "./provider.js";

type RunStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";
interface RunRecord { id: string; request: JudgmentRequest; status: RunStatus; result?: JudgmentResult; error?: string; events: PublicEvent[]; listeners: Set<ServerResponse>; controller: AbortController }

export function createPiServer(options: { token: string; provider: RoleProvider; maxBodyBytes?: number; heartbeatMs?: number }) {
  const runs = new Map<string, RunRecord>(); const queue: RunRecord[] = []; let active = false; const maxBodyBytes = options.maxBodyBytes ?? 32 * 1024 * 1024; const heartbeatMs = options.heartbeatMs ?? 15_000;
  const pump = () => { if (active || !queue.length) return; const next = queue.shift()!; if (next.status === "cancelled") { pump(); return; } active = true; const run = next; run.status = "running"; const emit = (event: Omit<PublicEvent, "source_seq">) => { const pub = { ...event, source_seq: run.events.length + 1 }; run.events.push(pub); for (const response of run.listeners) response.write(`id: ${pub.source_seq}\nevent: ${pub.type}\ndata: ${JSON.stringify(pub.data ?? {})}\n\n`); }; void runWorkflow(run.id, run.request, options.provider, emit, run.controller.signal).then((result) => { run.result = validateJudgmentResult(result, run.request, run.id); run.status = "succeeded"; emit({ type: "run.completed", data: { run_id: run.id } }); }).catch((error: unknown) => { run.error = error instanceof Error ? error.message : String(error); run.status = run.controller.signal.aborted ? "cancelled" : "failed"; emit({ type: run.status === "cancelled" ? "run.cancelled" : "run.failed", data: { run_id: run.id, error: run.error } }); }).finally(() => { for (const response of run.listeners) response.end(); run.listeners.clear(); active = false; pump(); }); };
  const authenticate = (req: IncomingMessage, res: ServerResponse) => { if (req.headers.authorization !== `Bearer ${options.token}`) { res.writeHead(401, { "content-type": "application/json" }); res.end(JSON.stringify({ error: "unauthorized" })); return false; } return true; };
  const readBody = async (req: IncomingMessage): Promise<unknown> => { const length = Number(req.headers["content-length"] ?? 0); if (length > maxBodyBytes) throw new Error("request body too large"); const chunks: Buffer[] = []; let total = 0; for await (const chunk of req) { const data = Buffer.from(chunk); total += data.length; if (total > maxBodyBytes) throw new Error("request body too large"); chunks.push(data); } return JSON.parse(Buffer.concat(chunks).toString("utf8")); };
  const handler = async (req: IncomingMessage, res: ServerResponse) => { if (!authenticate(req, res)) return; const url = new URL(req.url ?? "/", "http://127.0.0.1"); const match = url.pathname.match(/^\/internal\/v1\/runs\/([^/]+)(?:\/(events|result|cancel))?$/);
    if (req.method === "GET" && url.pathname === "/internal/v1/health") { res.writeHead(200, { "content-type": "application/json" }); res.end(JSON.stringify({ protocol_version: "1", pi_version: "0.84.1", workflow_version: "1", running: active })); return; }
    if (!match) { res.writeHead(404); res.end(); return; } const id = decodeURIComponent(match[1]); const suffix = match[2];
    if (req.method === "PUT" && !suffix) { if (runs.has(id)) { res.writeHead(200, { "content-type": "application/json" }); res.end(JSON.stringify({ run_id: id, status: runs.get(id)!.status })); return; } let request: JudgmentRequest; try { request = validateJudgmentRequest(await readBody(req)); } catch (error) { res.writeHead(400, { "content-type": "application/json" }); res.end(JSON.stringify({ error: String(error instanceof Error ? error.message : error) })); return; } const run: RunRecord = { id, request, status: "queued", events: [], listeners: new Set(), controller: new AbortController() }; runs.set(id, run); queue.push(run); pump(); res.writeHead(202, { "content-type": "application/json" }); res.end(JSON.stringify({ run_id: id, status: run.status })); return; }
    const run = runs.get(id); if (!run) { res.writeHead(404); res.end(); return; }
    if (req.method === "POST" && suffix === "cancel") { run.controller.abort(); if (run.status === "queued") run.status = "cancelled"; res.writeHead(202, { "content-type": "application/json" }); res.end(JSON.stringify({ run_id: id, status: run.status })); return; }
    if (req.method === "GET" && suffix === "result") { if (run.status === "succeeded") { res.writeHead(200, { "content-type": "application/json" }); res.end(JSON.stringify(run.result)); } else if (run.status === "failed" || run.status === "cancelled") { res.writeHead(409, { "content-type": "application/json" }); res.end(JSON.stringify({ run_id: id, status: run.status, error: run.error })); } else { res.writeHead(202, { "content-type": "application/json" }); res.end(JSON.stringify({ run_id: id, status: run.status })); } return; }
    if (req.method === "GET" && suffix === "events") { const after = Number(url.searchParams.get("after_source_seq") ?? 0); res.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive" }); for (const event of run.events.filter((entry) => entry.source_seq > after)) res.write(`id: ${event.source_seq}\nevent: ${event.type}\ndata: ${JSON.stringify(event.data ?? {})}\n\n`); if (["succeeded", "failed", "cancelled"].includes(run.status)) res.end(); else {
      // 单个角色真实耗时可达 100 秒以上，长间隔会让 HTTP 客户端的读超时把健康的
      // 流掐断。心跳注释帧只维持连接，不占事件序号，客户端解析时天然忽略。
      const heartbeat = setInterval(() => { if (!res.writableEnded) res.write(`: keep-alive\n\n`); }, heartbeatMs);
      const stop = () => { clearInterval(heartbeat); run.listeners.delete(res); };
      run.listeners.add(res); res.on("close", stop); res.on("finish", stop); req.on("close", stop);
    } return; }
    if (req.method === "GET" && !suffix) { res.writeHead(200, { "content-type": "application/json" }); res.end(JSON.stringify({ run_id: id, status: run.status, error: run.error })); return; }
    res.writeHead(405); res.end();
  };
  const server = createServer((req, res) => { void handler(req, res).catch((error) => { if (!res.headersSent) res.writeHead(500, { "content-type": "application/json" }); res.end(JSON.stringify({ error: String(error) })); }); });
  return { listen: (port: number, host: string) => new Promise<{ host: string; port: number }>((resolve) => { server.listen(port, host, () => { const address = server.address(); resolve({ host, port: typeof address === "object" && address ? address.port : port }); }); }), close: () => new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())) };
}
